version: "3.7"
services:
    app:
        build:
            context: .
        restart: unless-stopped
        tty: true
        container_name: app
        environment:
            APP_NAME: "Laravel with Live wire"
        volumes:
            - ./:/var/www/app
            - /var/www/app/vendor
        ports:
            - "8090:80"
        networks:
            - app

    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        tty: true
        expose:
            - 63791
        volumes:
            - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
            - redisdata:/data
        networks:
            - app

    #MySQL Service
    database:
        image: mysql:latest
        container_name: database
        restart: unless-stopped
        tty: true
        ports:
            - "53062:3306"
        environment:
            MYSQL_DATABASE: app
            DB_USERNAME: app
            DB_PASSWORD: password
            MYSQL_ROOT_PASSWORD: password
        volumes:
            - dbdata:/var/lib/mysql/
        networks:
            - app

networks:
    app:
        driver: bridge
        name: app

#Volumes
volumes:
    dbdata:
        driver: local
    redisdata:
        driver: local
